service: sunchirp-api
frameworkVersion: '2 || 3'

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  httpApi:
    cors: true

functions:
  #getGpsFromZip:
  #  handler: src/handlers/getGpsFromZip.handler
  #  events:
  #    - httpApi:
  #        path: /gps/{zipCode}
  #        method: get
  #getSunsetFromZip:
  #  handler: src/handlers/getSunsetFromZip.handler
  #  events:
  #    - httpApi:
  #        path: /sunset/{zipCode}
  #        method: get
  getSunsetFromGPS:
    handler: src/handlers/getSunsetFromGPS.handler
    events:
      - httpApi:
          path: /sunset
          method: post

custom:
  customDomain:
    domainName: api.sunchirp.com
    basePath: 'v1'
    certificateName: api.sunchirp.com
    createRoute53Record: true
    endpointType: regional
    apiType: http
