service: sunchirp-api
frameworkVersion: '2 || 3'

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'prod'}
  region: us-east-1

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

custom:
  customDomain:
    domainName: api.sunchirp.com
    basePath: 'v1'
    certificateName: api.sunchirp.com
    createRoute53Record: true
    endpointType: regional
    apiType: http
